#!/bin/bash

PIDFILE=/var/vcap/sys/run/variable.pid

case $1 in

  start)
    echo $$ > $PIDFILE

    exec /bin/sh 'while true; do echo "ZzZzZz..."; sleep 2; done'
    ;;

  stop)
    tail -1 $PIDFILE | xargs kill

    rm -rf $PIDFILE
    ;;

  *)
  echo "Usage: ctl {start|stop}" ;;
esac

exit 0
