// Code generated by counterfeiter. DO NOT EDIT.
package expectationfakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/bosh-fuzz-tests/expectation"
	bltclirunner "github.com/cloudfoundry-incubator/bosh-load-tests/action/clirunner"
)

type FakeExpectation struct {
	RunStub        func(cliRunner bltclirunner.Runner, taskId string) error
	runMutex       sync.RWMutex
	runArgsForCall []struct {
		cliRunner bltclirunner.Runner
		taskId    string
	}
	runReturns struct {
		result1 error
	}
	runReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeExpectation) Run(cliRunner bltclirunner.Runner, taskId string) error {
	fake.runMutex.Lock()
	ret, specificReturn := fake.runReturnsOnCall[len(fake.runArgsForCall)]
	fake.runArgsForCall = append(fake.runArgsForCall, struct {
		cliRunner bltclirunner.Runner
		taskId    string
	}{cliRunner, taskId})
	fake.recordInvocation("Run", []interface{}{cliRunner, taskId})
	fake.runMutex.Unlock()
	if fake.RunStub != nil {
		return fake.RunStub(cliRunner, taskId)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.runReturns.result1
}

func (fake *FakeExpectation) RunCallCount() int {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return len(fake.runArgsForCall)
}

func (fake *FakeExpectation) RunArgsForCall(i int) (bltclirunner.Runner, string) {
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.runArgsForCall[i].cliRunner, fake.runArgsForCall[i].taskId
}

func (fake *FakeExpectation) RunReturns(result1 error) {
	fake.RunStub = nil
	fake.runReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeExpectation) RunReturnsOnCall(i int, result1 error) {
	fake.RunStub = nil
	if fake.runReturnsOnCall == nil {
		fake.runReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.runReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeExpectation) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.runMutex.RLock()
	defer fake.runMutex.RUnlock()
	return fake.invocations
}

func (fake *FakeExpectation) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ expectation.Expectation = new(FakeExpectation)
